### ISSUE TITLE
Broken after updating

### ISSUE THREAD

**Issue by WSP-webmaster** [scweber/custom-comment-notifications#2]
After updating past 1.3 - 1.6 stopped getting emails to the site admin team. Turning off post author in Moderator Comment caused no email to fire. Adding additional email address did not function. Turning off plugin confirmed that core WP email was working. Turning plugin on, set to default settings caused only post author to get custom notification.

Trying to rollback to 1.3 until fix is forth-coming.

**Comment by scottalanweber** [comment]
Can you please try it again now using version 1.7? I have also cleaned up the directory structure so that it doesn't have duplicate directories and doesn't have any of the .svn directories.

**Comment by WSP-webmaster** [comment]
Updated plugin, now testing

**Comment by WSP-webmaster** [comment]
Updated, settings as follows

Format to display e-mail: HTML
Protect Comment Author Info in Email: No
Include Author in Moderation E-mails:  No

Site admin got no email alerting to comment in que for moderation (issue), test post author did not get email (as expected)

Turned off plug in, site admin got email from 2nd test post alerting to comment in que for moderation (basic wp function)

Unknown why moderation emails are still not being sent through? 

Q: could you add a field to specify directly in plugin who the moderation email should be sent to for testing purposes to see if its a brake in the plugin may be?

**Comment by scottalanweber** [comment]
Do you mean like the "Additional Recipients" section of the form?

**Comment by WSP-webmaster** [comment]
Just for testing so we can try and "FORCE" who the moderation emails are sent to because right now no moderation emails are being sent so im unclear if the plugin isn't getting the site admin email address from core wp or if the plugin itself is getting the sites admin email address but then does not fire off the moderation emails for whatever reason.

**Comment by scottalanweber** [comment]
Will the 'Additional Recipients' not serve this purpose?

**Comment by WSP-webmaster** [comment]
additional recipients does not function when an address is entered and "Include Author in Moderation E-mails:" is set to "no"  so it will not serve to put the site admins address into that field.

**Comment by WSP-webmaster** [comment]
also, when an additional address is entered and "Include Author in Moderation E-mails" is set to (yes) only the author gets notified, not the additional address or the site admin so "Author comment" works but "Moderator Comment" does not

**Comment by scottalanweber** [comment]
Ok, I found a little bug that should be related to this issue. Can you give it a try now?

**Comment by WSP-webmaster** [comment]
did you push out a wp update?

**Comment by scottalanweber** [comment]
No, sorry. I thought you were getting it from the Git Repo.  Let me push the update through WP.

**Comment by scottalanweber** [comment]
New version has been pushed to WP.

**Comment by WSP-webmaster** [comment]
bingo, that seems to have fixed the issue :+1:

**Comment by scottalanweber** [comment]
Perfect. Thank you for your patience and sorry about that.
